GET http://localhost:3000/test
Content-Type: application/json

{
    "myString": "Test succeeded!"
}

###

POST http://localhost:3000/addGameTest
Content-Type: application/json

###

GET http://localhost:3000/socketIOTest

###

GET https://quiz-game.azurewebsites.net/Server/proofOfConceptGetTest

###

GET http://localhost:4000/proofOfConceptGetTest